INFO:eval_calc_errors:-----------
INFO:eval_calc_errors:Parameters:
INFO:eval_calc_errors:- n_top: -1
INFO:eval_calc_errors:- visib_gt_min: -1.0
INFO:eval_calc_errors:- error_type: vsd
INFO:eval_calc_errors:- vsd_deltas: {'hb': 15.0, 'icbin': 15.0, 'icmi': 15.0, 'itodd': 5.0, 'lm': 15.0, 'lmo': 15.0, 'ruapc': 15.0, 'tless': 15.0, 'tudl': 15.0, 'tyol': 15.0, 'ycbv': 15.0, 'hope': 15.0}
INFO:eval_calc_errors:- vsd_taus: [0.05, 0.1, 0.15000000000000002, 0.2, 0.25, 0.3, 0.35000000000000003, 0.4, 0.45, 0.5]
INFO:eval_calc_errors:- vsd_normalized_by_diameter: True
INFO:eval_calc_errors:- max_sym_disc_step: 0.01
INFO:eval_calc_errors:- skip_missing: True
INFO:eval_calc_errors:- renderer_type: vispy
INFO:eval_calc_errors:- result_filenames: ['large-pbrreal-rgb-mmodel_tless-test_MultiHypothesis.csv']
INFO:eval_calc_errors:- results_path: C:\Users\XRSpecial\gigapose-1\gigaPose_datasets\results\large_\refined_multiple_predictions
INFO:eval_calc_errors:- eval_path: C:\Users\XRSpecial\gigapose-1\gigaPose_datasets\results\large_\refined_multiple_predictions
INFO:eval_calc_errors:- datasets_path: C:\Users\XRSpecial\gigapose-1\gigaPose_datasets\datasets
INFO:eval_calc_errors:- targets_filename: test_targets_bop19.json
INFO:eval_calc_errors:- out_errors_tpath: {eval_path}\{result_name}\{error_sign}\errors_{scene_id:06d}.json
INFO:eval_calc_errors:- num_workers: 2
INFO:eval_calc_errors:- eval_mode: localization
INFO:eval_calc_errors:-----------
INFO:eval_calc_errors:Processing: large-pbrreal-rgb-mmodel_tless-test_MultiHypothesis.csv
INFO:eval_calc_errors:Initializing renderer...
INFO:eval_calc_errors:Organizing estimation targets...
INFO:eval_calc_errors:Loading pose estimates...
INFO:eval_calc_errors:Organizing pose estimates...
INFO:eval_calc_errors:Processing scene 1 of tless...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\XRSpecial\miniconda3\envs\gigapose\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\XRSpecial\miniconda3\envs\gigapose\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\XRSpecial\miniconda3\envs\gigapose\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\XRSpecial\miniconda3\envs\gigapose\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\XRSpecial\miniconda3\envs\gigapose\lib\runpy.py", line 288, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\XRSpecial\miniconda3\envs\gigapose\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\XRSpecial\miniconda3\envs\gigapose\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\XRSpecial\gigapose-1\bop_toolkit\scripts\eval_calc_errors.py", line 550, in <module>
    pool = multiprocessing.Pool(p["num_workers"])
  File "C:\Users\XRSpecial\miniconda3\envs\gigapose\lib\multiprocessing\context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "C:\Users\XRSpecial\miniconda3\envs\gigapose\lib\multiprocessing\pool.py", line 212, in __init__
    self._repopulate_pool()
  File "C:\Users\XRSpecial\miniconda3\envs\gigapose\lib\multiprocessing\pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "C:\Users\XRSpecial\miniconda3\envs\gigapose\lib\multiprocessing\pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "C:\Users\XRSpecial\miniconda3\envs\gigapose\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\XRSpecial\miniconda3\envs\gigapose\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\XRSpecial\miniconda3\envs\gigapose\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\XRSpecial\miniconda3\envs\gigapose\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\XRSpecial\miniconda3\envs\gigapose\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
